### ISSUE TITLE
Migrating to Kotlin?

### ISSUE THREAD

**Issue by SAGARSURI** [commonsguy/cw-andexplore#1]
Any upcoming book where we can see this whole project in Kotlin and jetpack?

**Comment by commonsguy** [comment]
I am rewriting this book to be Kotlin/Jetpack now. I hope to release 0.4 by early April, though we'll see how things go. Stay tuned to https://commonsware.com for updates!

**Comment by SAGARSURI** [comment]
Awesome. I am eagerly waiting for the Kotlin and jetpack version.

**Comment by commonsguy** [comment]
@SAGARSURI FYI, [*Exploring Android*](https://commonsware.com/AndExplore) Version 0.4 is out, with the first 11 tutorials converted to Kotlin/Jetpack. Note, though, that the code is [in a different repository](https://gitlab.com/commonsguy/cw-andexplore).

**Comment by SAGARSURI** [comment]
You made my day. I am so damn excited to read it. Thanks a ton
