### ISSUE TITLE
Koin 2.0 as dependency injection?

### ISSUE THREAD

**Issue by SAGARSURI** [commonsguy/cw-andexplore#2]
I love the latest edition "Exploring Android". I do have a question regarding the Koin version that is used in the book. I saw the version is 1.0.2 and the latest version is 2.0 with some breaking changes. Will you be updating the book with Koin 2.0?

**Comment by commonsguy** [comment]
> I love the latest edition "Exploring Android".

Thanks for the kind words!

> I do have a question regarding the Koin version that is used in the book. I saw the version is 1.0.2 and the latest version is 2.0 with some breaking changes. Will you be updating the book with Koin 2.0?

Yes, I expect to upgrade to Koin 2.0 in the next book update.
